#!/bin/bash

echo "deb http://apt.anybox.fr/openerp common main" | sudo tee -a /etc/apt/sources.list
sudo apt-key adv --keyserver hkp://subkeys.pgp.net --recv-keys 0xE38CEB07
sudo aptitude update
sudo aptitude install openerp-server-system-build-deps
wget https://github.com/buildout/buildout/blob/master/bootstrap/bootstrap.py
sudo apt-get install virtualenv
virtualenv sandbox --no-setuptools
sandbox/bin/python bootstrap.py
bin/buildout
